resources:
  repositories:
    - repository: Utilities
      type: github
      endpoint: patrykpodlas
      name: patrykpodlas/Utilities

pr: none
trigger: none

variables:
  - group: Code Signing

jobs:
  - job: code_signing
    pool:
      name: vSphere
    steps:
      - task: AzureCLI@2
        displayName: Retrieve a list of existing signed files
        inputs:
          azureSubscription: 'Code-Signing'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          workingDirectory: '$(Build.StagingDirectory)'
          addSpnToEnvironment: true
          inlineScript: |
            Write-Output "--- Logging into storage account: $(storage-account), to retrieve a list of already signed files."
            $SecurePassword = ConvertTo-SecureString -String $(service-principal-secret) -AsPlainText -Force
            $PSCredential = New-Object System.Management.Automation.PSCredential($env:ServicePrincipalID, $SecurePassword)
            Connect-AzAccount -ServicePrincipal -Credential $PSCredential -Tenant $env:TenantID
            Write-Output "--- Logged into Azure."
            Write-Output "--- Searching for existing signed files."
            $ExistingFiles = Get-AzStorageBlob -Container $(destination-container) -Context $(Get-AzStorageAccount -ResourceGroupName $(storage-account-resource-group-name) -Name $(storage-account)).Context | Select-Object @{Name="Name";Expression={$_.Name.Split('/')[-1]}}
            Write-Output "Existing files:"
            $ExistingFiles = $ExistingFiles | Select-Object -ExpandProperty Name
            foreach ($ExistingFile in $ExistingFiles) {
                Write-Output $ExistingFile
            }
            Write-Host "##vso[task.setvariable variable=ExistingFiles;]$ExistingFiles"
      - task: PowerShell@2
        displayName: Signing
        inputs:
          targetType: 'inline'
          script: |
            Write-Output $ExistingFiles
            Write-Output "--- Retrieving a list of files to be signed."
            $Files = Get-ChildItem -Path "$(Build.Repository.LocalPath)" -Include '*.ps1' -Recurse | ForEach-Object {
                $FileContent = Get-Content $_ -ErrorAction Ignore
                if ($FileContent | Select-String -Pattern '#sign-me') {
                    $HasBeginBlock = $FileContent | Select-String -Pattern '# SIG # Begin signature block'
                    $HasEndBlock = $FileContent | Select-String -Pattern '# SIG # End signature block'
                    if (-not ($HasBeginBlock -and $HasEndBlock)) {
                        $FileName = $_.Name
                        $IsExisting = $ExistingFiles -contains $FileName
                        if (-not $IsExisting) {
                            Write-Output $_
                        }
                    }
                }
            }

            if ($Files) {
                Write-Output "--- Creating the code signing certificate from Azure Key Vault."
                New-Item "$(Build.StagingDirectory)\code_signing_certificate.pfx" -Value $(code-signing-certificate) | Out-Null
                if (Get-Item -Path "$(Build.StagingDirectory)\code_signing_certificate.pfx") {
                    Write-Output "--- Successfully created the code signing certificate."
                }

                Write-Output "--- Importing the code signing certificate."
                $Certificate = Import-PfxCertificate -CertStoreLocation Cert:\CurrentUser\My -FilePath "$(Build.StagingDirectory)\code_signing_certificate.pfx"

                Write-Output "--- Files to sign:"
                foreach ($File in $Files) {
                    Write-Output $File.Name
                }
                foreach ($File in $Files) {
                    Write-Output "--- Copying: $($File.Name) to $(Build.StagingDirectory) and signing."
                    $CopiedFile = Copy-Item -Path $File -Destination $(Build.StagingDirectory) -PassThru | Select-Object -ExpandProperty FullName
                    Set-AuthenticodeSignature -Certificate $Certificate -FilePath $CopiedFile -TimestampServer "http://timestamp.sectigo.com" | Select-Object Status, StatusMessage
                }

                Write-Output "--- Removing the certificate from the certificate store."
                Write-Output "--- Looking for certificate with thumbprint: $($Certificate.Thumbprint)."
                Get-Item -Path Cert:\CurrentUser\My\$Certificate.Thumbprint | Remove-Item
                Write-Output "--- Certificate removed from store."

                Write-Output "--- Removing the certificate from the staging directory."
                Get-Item -Path $(Build.StagingDirectory)\code_signing_certificate.pfx | Remove-Item
                Write-Output "--- Certificate removed from the staging directory."

                Write-Host "##vso[task.setvariable variable=Success]true"

            } elseif (!$Files) {
                Write-Output "--- Nothing to sign."
                Write-Host "##vso[task.setvariable variable=Success]false"
            }

      - task: AzureFileCopy@5
        displayName: Copying signed files to Azure Blob
        inputs:
          Destination: 'AzureBlob'
          azureSubscription: 'Code-Signing'
          SourcePath: $(Build.StagingDirectory)\*
          storage: $(storage-account)
          ContainerName: $(destination-container)
          BlobPrefix: 'powershell'
        condition: and(succeeded(), eq(variables['Success'], 'true'))

      - task: DeleteFiles@1
        displayName: Deleting files in staging directory
        inputs:
          SourceFolder: '$(Build.StagingDirectory)'
          Contents: '**'
          Recursive: true
        condition: and(succeeded(), eq(variables['Success'], 'true'))