# Include all of the repositories which you want this pipeline to scan for files to sign, make sure you also check them out in the jobs step checkout.
resources:
  repositories:
    - repository: Utilities
      type: github
      endpoint: patrykpodlas
      name: patrykpodlas/Utilities
    - repository: Azure
      type: github
      endpoint: patrykpodlas
      name: patrykpodlas/Azure
    - repository: VMware
      type: github
      endpoint: patrykpodlas
      name: patrykpodlas/VMware

  webhooks:
    - webhook: MyTrigger
      connection: Trigger-Utilities
      filters:
        - path: action
          value: closed

trigger:
  branches:
    include:
    - main # Trigger only on the main branch.
  paths:
    include:
    - '*' # Include all files within the repository.

pr: none # Do not trigger on PR, this is taken care of by the CI trigger.

variables:
  - group: Code Signing # This must include all the secrets, do not store the certificate in secure files, instead link the variable group to the Azure key vault and retrieve the secrets as well as the certificate from there.

jobs:
  - job: code_signing
    pool:
      vmImage: windows-latest # For this pipeline, this agent can be an online agent as it does not connect to any on-premises resources.
    steps:
      - checkout: self
      - checkout: Azure
      - checkout: VMware

      - task: AzurePowerShell@5
        displayName: Retrieve a list of signed files in blob storage
        inputs:
          azureSubscription: 'Code-Signing'
          ScriptType: 'FilePath'
          ScriptPath: '$(Build.Repository.LocalPath)\Utilities\code-signing\get-list-of-signed-files.ps1'
          ScriptArguments: >
            -StorageAccountResourceGroupName $(storage-account-resource-group-name)
            -StorageAccount $(storage-account)
            -DestinationContainer $(destination-container)
            -ExecutablesContainer $(executables-container)
          azurePowerShellVersion: 'LatestVersion'
          workingDirectory: '$(Build.StagingDirectory)'

      - task: PowerShell@2 # Scans the files in each repository, and then signs them. Note: Set-AuthenticodeSignature is not supported on non-Windows endpoints.
        displayName: Scanning and signing PowerShell scripts
        inputs:
          targetType: filePath
          filePath: '$(Build.Repository.LocalPath)\Utilities\code-signing\sign-powershell.ps1'
          arguments: >
            -CodeSigningCertificate $(code-signing-certificate)

      - task: PowerShell@2 # Scans the exe in each repository, and then signs them. Note: Set-AuthenticodeSignature is not supported on non-Windows endpoints.
        displayName: Scanning and signing executables
        inputs:
          targetType: filePath
          filePath: '$(Build.Repository.LocalPath)\Utilities\code-signing\sign-executables.ps1'
          arguments: >
            -CodeSigningCertificate $(code-signing-certificate)

      - task: AzurePowerShell@5
        displayName: Upload signed PowerShell scripts to blob storage
        condition: and(succeeded(), eq(variables['NeedToSignScripts'], 'true'))
        inputs:
          azureSubscription: 'Code-Signing'
          ScriptType: 'FilePath'
          ScriptPath: '$(Build.Repository.LocalPath)\Utilities\code-signing\upload-files-to-blob.ps1'
          ScriptArguments: >
            -StorageAccountResourceGroupName $(storage-account-resource-group-name)
            -StorageAccount $(storage-account)
            -DestinationContainer $(destination-container)
          azurePowerShellVersion: 'LatestVersion'
          workingDirectory: '$(Build.StagingDirectory)'

      - task: AzurePowerShell@5
        displayName: Upload signed executables to blob storage
        condition: and(succeeded(), eq(variables['NeedToSignExecutables'], 'true'))
        inputs:
          azureSubscription: 'Code-Signing'
          ScriptType: 'FilePath'
          ScriptPath: '$(Build.Repository.LocalPath)\Utilities\code-signing\upload-executables-to-blob.ps1'
          ScriptArguments: >
            -StorageAccountResourceGroupName $(storage-account-resource-group-name)
            -StorageAccount $(storage-account)
            -ExecutablesContainer $(executables-container)
          azurePowerShellVersion: 'LatestVersion'
          workingDirectory: '$(Build.StagingDirectory)'

      - task: DeleteFiles@1 # Cleaning up the stating directory.
        displayName: Deleting files in staging directory
        condition: or(eq(variables['NeedToSignScripts'], 'true'), eq(variables['NeedToSignExecutables'], 'true'))
        inputs:
          SourceFolder: '$(Build.StagingDirectory)'
          Contents: '**'
          Recursive: true